-- Read-only independent confirmation; verify exact BCM Test URL.
begin read only;
set local statement_timeout='30s';
select jsonb_build_object('project_expected','imvkhicfmidzbzsbhkzs','database_identity',(select system_identifier::text from pg_control_system()),'schema_digest',(select encode(sha256(convert_to(coalesce(jsonb_agg(item order by item::text),'[]'::jsonb)::text,'UTF8')),'hex') from (
  select jsonb_build_object('relation',n.nspname||'.'||c.relname,'oid',c.oid,'kind',c.relkind,'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,'acl',c.relacl,'owner',c.relowner) item
    from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','vb_private')
  union all select jsonb_build_object('column',a.attrelid,'n',a.attnum,'name',a.attname,'type',a.atttypid,'mod',a.atttypmod,'null',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid))
    from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where n.nspname in ('public','vb_private') and a.attnum>0 and not a.attisdropped
  union all select jsonb_build_object('function',p.oid,'name',n.nspname||'.'||p.proname,'args',p.proargtypes::text,'result',p.prorettype,'source_hash',encode(sha256(convert_to(p.prosrc,'UTF8')),'hex'),'definer',p.prosecdef,'config',p.proconfig,'acl',p.proacl,'owner',p.proowner)
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','vb_private')
  union all select jsonb_build_object('constraint',x.oid,'definition',pg_get_constraintdef(x.oid)) from pg_constraint x join pg_namespace n on n.oid=x.connamespace where n.nspname in ('public','vb_private')
  union all select jsonb_build_object('trigger',t.oid,'definition',pg_get_triggerdef(t.oid)) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','vb_private')
  union all select jsonb_build_object('policy',to_jsonb(p)) from pg_policies p where p.schemaname in ('public','vb_private')
  union all select jsonb_build_object('namespace',n.nspname,'acl',n.nspacl,'owner',n.nspowner) from pg_namespace n where n.nspname in ('public','vb_private')
) metadata),'extension_state',(select coalesce(jsonb_agg(to_jsonb(e) order by e.extname),'[]'::jsonb) from pg_extension e),'manifest_absent',to_regclass('vb_private.brand_map_race_runs') is null,'owned_functions_absent',to_regprocedure('public.vb_read_brand_map(uuid)') is null and to_regprocedure('public.vb_save_brand_asset(uuid,uuid,bigint,jsonb)') is null and to_regprocedure('public.vb_set_brand_parent(uuid,uuid,uuid,bigint)') is null and to_regprocedure('public.vb_confirm_brand_relationship(uuid,uuid,bigint)') is null and to_regprocedure('public.vb_review_brand_legal_link(uuid,uuid,uuid,bigint,bigint,jsonb)') is null and to_regprocedure('vb_private.brand_map_touch()') is null and to_regprocedure('vb_private.brand_map_initialize_slots()') is null and to_regprocedure('vb_private.brand_map_can_read(uuid)') is null and to_regprocedure('vb_private.brand_map_lock_write(uuid,boolean)') is null and to_regprocedure('vb_private.brand_map_mark_fingerprint(public.vb_marks)') is null,'owned_tables_absent',to_regclass('public.vb_brand_legal_links') is null and to_regclass('public.vb_brand_relationships') is null and to_regclass('public.vb_brand_assets') is null,'remaining_users',(select count(*) from auth.users where id in ('7da00277-4ee2-4719-bfa4-43e77f4fb6ed'::uuid,'eb1493cf-c9fe-4956-a57e-0ce120c55c02'::uuid)),'remaining_clients',(select count(*) from public.vb_clients where id='2ba5b51e-62d8-48db-915f-b273e84736bb'::uuid),'remaining_marks',(select count(*) from public.vb_marks where id in ('e618603b-0870-444b-b05c-002ec03d3497'::uuid,'a9ae4510-128c-4782-b5b7-e7b8b2fcea6c'::uuid,'c02015f4-14e3-4f15-9292-09774decc262'::uuid,'fb750360-1320-4bea-8e2a-f323f2176593'::uuid,'2b2bb3c7-56ae-4b22-8696-254abdc9bc81'::uuid,'c491758e-0988-491a-bf15-0e9d497ce306'::uuid)),'remaining_memberships',(select count(*) from vb_private.client_memberships where client_id='2ba5b51e-62d8-48db-915f-b273e84736bb'::uuid or user_id in ('7da00277-4ee2-4719-bfa4-43e77f4fb6ed'::uuid,'eb1493cf-c9fe-4956-a57e-0ce120c55c02'::uuid)),'remaining_staff',(select count(*) from vb_private.staff_members where user_id='eb1493cf-c9fe-4956-a57e-0ce120c55c02'::uuid),'remaining_preferences',(select count(*) from public.vb_service_preferences where client_id='2ba5b51e-62d8-48db-915f-b273e84736bb'::uuid),'remaining_audit_rows',(select count(*) from vb_private.audit_events where client_id='2ba5b51e-62d8-48db-915f-b273e84736bb'::uuid or actor_id in ('7da00277-4ee2-4719-bfa4-43e77f4fb6ed'::uuid,'eb1493cf-c9fe-4956-a57e-0ce120c55c02'::uuid)),'remaining_active_run_connections',(select count(*) from pg_stat_activity where pid<>pg_backend_pid() and datname=current_database() and application_name like 'bm-race-813aabca-%' and state<>'idle')) as brand_map_race_postcheck;
rollback;
