import test from 'node:test';import assert from 'node:assert/strict';
import {contactValues,saveContact,changeEmail,resetPassword} from '../auth/account.mjs';
function mock(role='client'){const calls=[];return {calls,auth:{getUser:async()=>({data:{user:{email:'old@example.com'}}}),mfa:{getAuthenticatorAssuranceLevel:async()=>({data:{currentLevel:'aal1',nextLevel:'aal1'}})},updateUser:async(...args)=>{calls.push(args);return {};},resetPasswordForEmail:async(...args)=>{calls.push(args);return {};}},rpc:async(name,args)=>{if(name==='vb_session_role')return {data:role};calls.push([name,args]);return {data:{contact_name:args.contact_name}};}};}
test('contact validation trims and allows blank optional email',()=>{assert.deepEqual(contactValues(' Mario ',' '),{name:'Mario',email:null});assert.throws(()=>contactValues(' ','x@example.com'));assert.throws(()=>contactValues('Mario','invalid'));});
test('contact save only sends allowed fields and stale version',async()=>{const db=mock();await saveContact(db,{id:'one',updated_at:'version',portal_enabled:true},'Mario','');assert.deepEqual(db.calls[0],['vb_update_my_contact',{target_client:'one',expected_updated_at:'version',contact_name:'Mario',contact_email:null}]);});
test('staff/denied role cannot initiate client changes',async()=>{for(const role of ['staff','denied']){const db=mock(role);await assert.rejects(saveContact(db,{id:'x'},'Mario',''));await assert.rejects(changeEmail(db,'new@example.com','https://vb.example'));await assert.rejects(resetPassword(db,'https://vb.example'));assert.equal(db.calls.length,0);}});
test('email change uses Auth and login callback, never contact save',async()=>{const db=mock();await changeEmail(db,'new@example.com','https://vb.example');assert.deepEqual(db.calls,[[{email:'new@example.com'},{emailRedirectTo:'https://vb.example/login.html'}]]);});
test('unchanged email rejected without sending',async()=>{const db=mock();await assert.rejects(changeEmail(db,'OLD@example.com','https://vb.example'));assert.equal(db.calls.length,0);});
test('password reset goes only to verified current account email',async()=>{const db=mock();await resetPassword(db,'https://vb.example');assert.deepEqual(db.calls,[['old@example.com',{redirectTo:'https://vb.example/login.html'}]]);});
