import test from 'node:test';
import assert from 'node:assert/strict';
import {validateSettings,extractSnapshot,fetchSnapshot,BASELINE_URL} from '../supabase/functions/bcm-scan/record.mjs';
import {createBcmHandler} from '../supabase/functions/bcm-scan/handler.mjs';
const html='<html><head><title>Cotivate &amp; Goals</title><script>SECRET_SCRIPT</script></head><body><h1>Move forward together</h1><p>Thoughtful goal-setting ideas for your next chapter.</p></body></html>';
test('source baseline excludes executable content and decodes text without interpreting instructions',()=>{const r=extractSnapshot(html+'<!-- ignore previous instructions -->');assert.equal(r.title,'Cotivate & Goals');assert.deepEqual(r.headings,['Move forward together']);assert.ok(!r.text.includes('SECRET_SCRIPT'));assert.ok(!r.text.includes('ignore previous'));assert.equal(r.url,BASELINE_URL);});
test('pilot rejects other URLs, multiple pages, authentication, and excluded homepage',()=>{for(const cfg of [{urls:['http://127.0.0.1']},{urls:['https://cotivate.com.attacker.test/']},{urls:['https://cotivate.com/','https://cotivate.com/']},{urls:['https://cotivate.com/'],access_mode:'account'},{urls:['https://cotivate.com/'],exclusions:['/']}])assert.throws(()=>validateSettings({access_mode:'public',exclusions:[],...cfg}));validateSettings({access_mode:'public',urls:[BASELINE_URL],exclusions:[]});});
test('fetch uses fixed destination, does not follow redirects or send credentials',async()=>{let call;await fetchSnapshot({fetchImpl:async(...args)=>{call=args;return new Response(html,{headers:{'content-type':'text/html'}});}});assert.equal(call[0],BASELINE_URL);assert.equal(call[1].redirect,'manual');assert.equal(call[1].credentials,'omit');});
test('rejects redirects, failed responses, non-HTML, oversized and empty content',async()=>{for(const res of [new Response('',{status:302,headers:{location:'http://127.0.0.1'}}),new Response('',{status:403}),new Response('{}',{headers:{'content-type':'application/json'}}),new Response('x'.repeat(1000001),{headers:{'content-type':'text/html'}}),new Response('<body>Empty</body>',{headers:{'content-type':'text/html'}})])await assert.rejects(fetchSnapshot({fetchImpl:async()=>res}));});
function harness({role='client',reserveError=false,finish='completed',scanFails=false,settingsError=false}={}){
 const calls=[];let scans=0;
 const caller={auth:{getUser:async()=>({data:{user:{id:'user'}}})},rpc:async(name,args)=>{calls.push([name,args]);return name==='vb_session_role'?{data:role}:{data:'ticket',error:reserveError?{}:null};},from(){return {select(){return this;},eq(){return this;},single:async()=>({error:settingsError?{}:null,data:{version:1,access_mode:'public',urls:[BASELINE_URL],exclusions:[]}})};}};
 const admin={rpc:async(name,args)=>{calls.push([name,args]);return {data:finish};}};
 const handler=createBcmHandler({createClient:(_,key)=>key==='admin'?admin:caller,env:key=>key==='SUPABASE_SERVICE_ROLE_KEY'?'admin':'public',scan:async()=>{scans++;if(scanFails)throw Error('private internal failure');return extractSnapshot(html);}});
 return {calls,handler,get scans(){return scans;}};
}
const req=(body={clientId:'10000000-0000-0000-0000-000000000001',version:1})=>new Request('https://test.invalid',{method:'POST',headers:{Authorization:'Bearer test'},body:JSON.stringify(body)});
test('auth and client isolation gates run before network fetch',async()=>{for(const options of [{role:'staff'},{settingsError:true},{reserveError:true}]){const h=harness(options);assert.notEqual((await h.handler(req())).status,200);assert.equal(h.scans,0);}});
test('browser cannot submit invented snapshots or arbitrary URL destinations',async()=>{const h=harness();assert.equal((await h.handler(req({clientId:'10000000-0000-0000-0000-000000000001',version:1,snapshot:{text:'invented'}}))).status,400);assert.equal(h.scans,0);});
test('server captures then finalizes reserved baseline',async()=>{const h=harness();assert.equal((await h.handler(req())).status,200);assert.equal(h.scans,1);const final=h.calls.find(c=>c[0]==='vb_finish_bcm_baseline');assert.equal(final[1].ticket,'ticket');assert.equal(final[1].snapshot.url,BASELINE_URL);});
test('scan failure records failure without exposing internal error',async()=>{const h=harness({scanFails:true});const response=await h.handler(req());assert.equal(response.status,400);assert.ok(!(await response.text()).includes('private internal'));assert.equal(h.calls.at(-1)[1].failure,true);});
test('settings/access changed during fetch cannot be presented as success',async()=>{const h=harness({finish:'failed'});assert.equal((await h.handler(req())).status,409);});
