import test from 'node:test';
import assert from 'node:assert/strict';
import {bcmValues,loadBcmSettings,saveBcmSettings} from '../auth/bcm.mjs';
const draft=()=>({urls:' https://example.com/products\nhttps://example.com/features ',exclude:'/account\n/billing',access:'public',frequency:'Weekly',categories:['product_names','logos'],password:'MUST_NOT_SEND',client_id:'other',version:999,enabled:true});
function fake({role='client',error=null,saved=null}={}){const calls=[];return {calls,auth:{getUser:async()=>({data:{user:{id:'one'}}}),mfa:{getAuthenticatorAssuranceLevel:async()=>({data:{currentLevel:'aal1',nextLevel:'aal1'}})}},rpc:async(name,args)=>{if(name==='vb_session_role')return {data:role};calls.push([name,args]);return {data:saved,error};},from(table){calls.push(table);return {select(){return this;},eq(k,v){calls.push([k,v]);return this;},maybeSingle:async()=>({data:saved,error})};}};}
test('save allowlist excludes credentials, ownership and activation fields',async()=>{const db=fake({saved:{version:1}});const result=await saveBcmSettings(db,'client-one',0,draft(),true);assert.equal(result.version,1);const [name,args]=db.calls[0];assert.equal(name,'vb_save_bcm_settings');assert.equal(args.target_client,'client-one');assert.equal(args.expected_version,0);assert.deepEqual(Object.keys(args.details).sort(),['access_mode','categories','exclusions','frequency','urls']);assert.equal(JSON.stringify(args).includes('MUST_NOT_SEND'),false);assert.deepEqual(args.details.urls,['https://example.com/products','https://example.com/features']);});
test('requires permission and valid version before writing',async()=>{const db=fake();await assert.rejects(saveBcmSettings(db,'a',0,draft(),false));await assert.rejects(saveBcmSettings(db,'a',undefined,draft(),true));assert.equal(db.calls.length,0);});
test('rejects URL credentials, queries, fragments, invalid protocol and duplicate URLs',()=>{for(const urls of ['https://user:pass@example.com','https://example.com?token=x','https://example.com/#token','javascript:alert(1)','https://example.com\nhttps://example.com',' ','https://'])assert.throws(()=>bcmValues({...draft(),urls},true));});
test('rejects unsupported options, malformed categories and exclusions',()=>{for(const patch of [{categories:[]},{categories:['unknown']},{categories:['logos','logos']},{frequency:'Daily'},{access:'admin'},{exclude:'https://example.com/account'},{exclude:'/account?secret=x'}])assert.throws(()=>bcmValues({...draft(),...patch},true));});
test('supports dedicated-account preference without collecting a secret',()=>{const data=bcmValues({...draft(),access:'account'},true);assert.equal(data.access_mode,'account');assert.equal(data.password,undefined);});
test('load targets selected client, empty row is distinct from failed loading',async()=>{const db=fake();assert.equal(await loadBcmSettings(db,'client-two'),null);assert.deepEqual(db.calls,['vb_bcm_settings',['client_id','client-two']]);await assert.rejects(loadBcmSettings(fake({error:{code:'42P01'}}),'a'),/Database setup is pending/);});
test('client role required before every load/save',async()=>{for(const role of ['staff','denied']){const db=fake({role});await assert.rejects(loadBcmSettings(db,'a'));await assert.rejects(saveBcmSettings(db,'a',0,draft(),true));assert.equal(db.calls.length,0);}});
test('conflict requires explicit reload, never retries or overwrites',async()=>{const db=fake({error:{code:'40001'}});await assert.rejects(saveBcmSettings(db,'a',1,draft(),true),/changed elsewhere/);assert.equal(db.calls.length,1);});
test('missing backend cannot be reported as successful saving',async()=>{await assert.rejects(saveBcmSettings(fake({error:{code:'PGRST202'}}),'a',0,draft(),true),/Database setup is pending/);});
