import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from './vendor/marked.mjs';

export const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const marker = '<!-- Generated by tools/build-blog.mjs -->';
const escape = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const safeUrl = value => {
  const url = String(value || '').trim();
  return /[\u0000-\u0020]/.test(url) || (/^[a-z][a-z\d+.-]*:/i.test(url) && !/^(https?:|mailto:)/i.test(url)) ? '#' : url;
};
marked.use({renderer: {
  html({text}) { return escape(text); },
  link({href, title, tokens}) { return `<a href="${escape(safeUrl(href))}"${title ? ` title="${escape(title)}"` : ''}>${this.parser.parseInline(tokens)}</a>`; },
  image({href, text}) { return `<img src="${escape(safeUrl(href))}" alt="${escape(text)}" loading="lazy">`; }
}});

export function readPosts(sourceDir, preview = false, today = new Date().toISOString().slice(0,10)) {
  return fs.readdirSync(sourceDir).filter(name => name.endsWith('.md')).map(name => {
    const slug = name.slice(0,-3);
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw new Error(`Invalid article filename: ${name}`);
    const source = fs.readFileSync(path.join(sourceDir,name),'utf8').replace(/\r\n/g,'\n');
    const match = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
    if (!match) throw new Error(`${name}: missing article details.`);
    const meta = {};
    for (const line of match[1].split('\n').filter(line => line.trim())) {
      const split = line.indexOf(':');
      if (split < 1) throw new Error(`${name}: invalid detail line.`);
      const key = line.slice(0,split).trim();
      if (Object.hasOwn(meta,key)) throw new Error(`${name}: duplicate ${key}.`);
      meta[key] = line.slice(split+1).trim().replace(/^(["'])(.*)\1$/,'$2');
    }
    for (const key of ['title','description','date','author','category']) if (!meta[key]) throw new Error(`${name}: missing ${key}.`);
    if (!/^\d{4}-\d{2}-\d{2}$/.test(meta.date) || !Number.isFinite(Date.parse(meta.date)) || new Date(meta.date).toISOString().slice(0,10) !== meta.date) throw new Error(`${name}: invalid date.`);
    const status = meta.status || 'draft';
    if (!['draft','sample','published'].includes(status)) throw new Error(`${name}: invalid status.`);
    if (meta.image && (!/^images\/blog\/[a-zA-Z0-9_./-]+\.(png|jpe?g|webp|avif)$/i.test(meta.image) || meta.image.split('/').includes('..') || !meta.imageAlt || !fs.existsSync(path.join(root,meta.image)))) throw new Error(`${name}: image must exist under images/blog and include imageAlt.`);
    const order = Number(meta.order || 0);
    if (!Number.isFinite(order)) throw new Error(`${name}: invalid order.`);
    return {...meta, slug, status, order, scheduled:meta.date > today, html:marked.parse(match[2])};
  }).filter(post => preview || (post.status === 'published' && !post.scheduled))
    .sort((a,b) => b.date.localeCompare(a.date) || b.order-a.order || a.slug.localeCompare(b.slug));
}
const date = value => new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T00:00:00Z`));
const label = post => post.status === 'sample' ? 'Sample article · Preview only' : post.status === 'draft' ? 'Draft · Preview only' : post.scheduled ? 'Scheduled · Preview only' : '';
function shell(title, description, body, prefix, preview) {
  return `<!DOCTYPE html>\n${marker}\n<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escape(title)} — Venture Branding</title><meta name="description" content="${escape(description)}">${preview ? '<meta name="robots" content="noindex,nofollow">' : ''}
<link rel="icon" href="${prefix}images/09.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600;9..144,700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="${prefix}blog/assets/blog.css"><script src="${prefix}blog/assets/blog.js" defer></script></head><body>
<a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="shell header-inner">
<a class="brand" href="${prefix}v8.html" aria-label="Venture Branding home"><img src="${prefix}images/02.png" alt="Venture Branding"></a>
<button class="menu" aria-expanded="false" aria-controls="blog-navigation" type="button">Menu</button>
<nav class="navigation" id="blog-navigation" aria-label="Primary"><a href="${prefix}v8.html#about">About</a><a href="${prefix}v8.html#services">Services</a><a href="${prefix}blog.html" aria-current="page">Blog</a><a href="${prefix}v8.html#contact">Contact</a><a class="cta" href="${prefix}v8.html#contact">Book a Consultation</a></nav></div></header>
${preview ? '<div class="preview-note"><strong>Local review preview.</strong> Samples and drafts shown here are excluded from the normal blog build.</div>' : ''}
<main id="main">${body}</main><footer class="site-footer"><div class="shell footer-inner"><p>© 2026 Venture Branding, Inc. All rights reserved.</p><nav class="footer-links" aria-label="Footer"><a href="${prefix}v8.html">Home</a><a href="${prefix}blog.html">Blog</a><a href="${prefix}v8.html#contact">Contact</a></nav></div></footer></body></html>\n`;
}
function card(post, prefix) {
  const href = `${prefix}blog/posts/${post.slug}.html`;
  const search = [post.title,post.description,post.author,post.category].join(' ').toLocaleLowerCase();
  return `<article class="card" data-search="${escape(search)}">${post.image ? `<img class="card-image" src="${prefix}${escape(post.image)}" alt="${escape(post.imageAlt)}" loading="lazy">` : `<div class="card-motif" aria-hidden="true"><img src="${prefix}images/09.png" alt=""></div>`}
<div class="card-copy">${label(post) ? `<span class="badge">${label(post)}</span>` : ''}<div class="meta"><span>${escape(post.category)}</span><time datetime="${post.date}">${date(post.date)}</time></div><h3><a href="${href}">${escape(post.title)}</a></h3><p>${escape(post.description)}</p><span class="card-author">By ${escape(post.author)}</span><a class="read" href="${href}" aria-label="Read ${escape(post.title)}">Read article <span aria-hidden="true">→</span></a></div></article>`;
}
function listing(posts, preview) {
  const body = `<section class="hero"><div class="shell"><span class="eyebrow">The Venture Branding journal</span><h1>Ideas worth building.<br>Brands worth <em>protecting.</em></h1><p>Thoughtful reading on trademarks, brand identity, and the decisions that move a business forward.</p></div></section>
<section class="shell blog-content" aria-labelledby="articles-title"><div class="toolbar"><div><h2 id="articles-title">${preview ? 'Article preview' : 'Latest articles'}</h2><p class="count" id="result-count" role="status">${posts.length} ${posts.length === 1 ? 'article' : 'articles'}</p></div>${posts.length ? '<div class="search" hidden><label for="blog-search">Search the journal</label><input id="blog-search" type="search" placeholder="Title, topic, or author" aria-controls="article-list"></div>' : ''}</div>
${posts.length ? `<div class="cards" id="article-list">${posts.map(post => card(post,'')).join('')}</div><div class="empty" id="no-results" hidden><h2>No matching articles.</h2><p>Try a different title, topic, or author.</p><button class="reset" id="clear-search" type="button">Clear search</button></div>` : '<div class="empty"><span class="eyebrow">The journal</span><h2>Our first articles are on their way.</h2><p>We’re preparing practical reading for founders. In the meantime, explore how Venture Branding can support your next step.</p><a class="button" href="v8.html#services">Explore Services <span aria-hidden="true">→</span></a></div>'}</section>`;
  return shell('Blog','Thoughtful reading on trademarks, brand identity, and building a business.',body,'',preview);
}
function article(post, posts, preview) {
  const prefix = '../../';
  const related = posts.filter(item => item.slug !== post.slug).sort((a,b) => Number(b.category===post.category)-Number(a.category===post.category)).slice(0,3);
  const body = `<article><header class="shell article-top"><a class="back" href="../../blog.html">← Back to the journal</a><p class="eyebrow">${escape(post.category)}</p>${label(post) ? `<span class="badge">${label(post)}</span>` : ''}<h1>${escape(post.title)}</h1><p class="description">${escape(post.description)}</p><div class="byline"><span>By ${escape(post.author)}</span><time datetime="${post.date}">${date(post.date)}</time></div></header>
<div class="article-paper"><div class="article-body">${post.status === 'sample' ? '<p class="reading-note"><strong>Layout sample.</strong> This article is for reviewing the blog design. It is not published content or legal guidance.</p>' : ''}${post.image ? `<img class="article-cover" src="${prefix}${escape(post.image)}" alt="${escape(post.imageAlt)}">` : ''}${post.html}<div class="article-end"><a href="../../blog.html">← All articles</a><a href="../../v8.html#services">Explore our services →</a></div></div></div></article>
${related.length ? `<section class="shell related" aria-labelledby="related-title"><h2 id="related-title">Related reading</h2><div class="cards">${related.map(item => card(item,prefix)).join('')}</div></section>` : ''}`;
  return shell(post.title,post.description,body,prefix,preview);
}
export function build({preview=false,outDir=preview ? path.join(root,'work/blog-preview') : root,sourceDir=path.join(root,'content/posts')}={}) {
  const posts = readPosts(sourceDir,preview);
  // Validate and render before touching the previous build.
  const index = listing(posts,preview);
  const pages = posts.map(post => [post.slug,article(post,posts,preview)]);
  const articleDir = path.join(outDir,'blog/posts');
  fs.mkdirSync(articleDir,{recursive:true});
  for (const filename of fs.readdirSync(articleDir)) {
    if (filename.endsWith('.html') && !posts.some(post => `${post.slug}.html` === filename)) {
      const filepath = path.join(articleDir,filename);
      if (fs.readFileSync(filepath,'utf8').includes(marker)) fs.unlinkSync(filepath);
    }
  }
  if (outDir !== root) {
    fs.mkdirSync(path.join(outDir,'blog/assets'),{recursive:true});
    for (const filename of ['blog.css','blog.js']) fs.copyFileSync(path.join(root,'blog/assets',filename),path.join(outDir,'blog/assets',filename));
    fs.mkdirSync(path.join(outDir,'images'),{recursive:true});
    for (const filename of ['02.png','09.png','Cosey_Marion__1994x1058-2.jpg']) fs.copyFileSync(path.join(root,'images',filename),path.join(outDir,'images',filename));
    for (const post of posts.filter(post => post.image)) {
      fs.mkdirSync(path.dirname(path.join(outDir,post.image)),{recursive:true});
      fs.copyFileSync(path.join(root,post.image),path.join(outDir,post.image));
    }
    let home = fs.readFileSync(path.join(root,'v8.html'),'utf8');
    if (preview) home = home.replace('<head>','<head>\n<meta name="robots" content="noindex,nofollow">');
    fs.writeFileSync(path.join(outDir,'v8.html'),home);
  }
  fs.writeFileSync(path.join(outDir,'blog.html'),index);
  for (const [slug,html] of pages) fs.writeFileSync(path.join(articleDir,`${slug}.html`),html);
  return {count:posts.length,outDir};
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.some(arg => arg !== '--preview')) throw new Error('Usage: node tools/build-blog.mjs [--preview]');
  const result = build({preview:args.includes('--preview')});
  console.log(`Built ${result.count} article(s) in ${result.outDir}`);
}
