import test from 'node:test';import assert from 'node:assert/strict';
import {digestValues,createDigestRepository} from '../auth/digest.mjs';
const valid={categories:['bcm','use_history'],frequency:'weekly',delivery:'account'};
function db({user=true,role='client',list=[],rpcResult}={}){const calls=[];return {calls,auth:{getUser:async()=>({data:{user:user?{id:'u1'}:null}}),mfa:{getAuthenticatorAssuranceLevel:async()=>({data:{currentLevel:'aal1',nextLevel:'aal1'}})}},rpc:async(name,args)=>{calls.push([name,args]);return name==='vb_session_role'?{data:role}:rpcResult?rpcResult(name,args):{data:{client_id:'c1',version:1}};},from(){return {select(){return this},eq(){return this},order(){return this},limit:async()=>({data:list}),maybeSingle:async()=>({data:null})}}};}
test('digest settings reject unsupported sources, duplicate sources, email and invalid frequencies',()=>{for(const v of [{...valid,categories:[]},{...valid,categories:['watch']},{...valid,categories:['bcm','bcm']},{...valid,delivery:'email'},{...valid,frequency:'immediate'}])assert.throws(()=>digestValues(v));assert.deepEqual(digestValues(valid),valid);});
test('Production disabled makes no requests',()=>{const d=db();assert.equal(createDigestRepository(d,{enabled:false}),null);assert.deepEqual(d.calls,[]);});
test('signed-out and wrong-role accounts cannot save or generate',async()=>{for(const options of [{user:false},{role:'staff'}]){const d=db(options),r=createDigestRepository(d,{enabled:true});await assert.rejects(()=>r.save('c1',0,valid));await assert.rejects(()=>r.sample('c1',1));assert.equal(d.calls.some(([n])=>n==='vb_generate_digest_sample'||n==='vb_save_digest_preferences'),false);}});
test('preferences are scoped and server creates sample from saved version',async()=>{const d=db(),r=createDigestRepository(d,{enabled:true});await r.save('c1',0,valid);await r.sample('c1',1);assert.deepEqual(d.calls.find(([n])=>n==='vb_save_digest_preferences')[1],{target_client:'c1',expected_version:0,details:valid});assert.deepEqual(d.calls.find(([n])=>n==='vb_generate_digest_sample')[1],{target_client:'c1',expected_version:1});});
test('inbox filters client mismatch and refuses mismatched opened message',async()=>{const r=createDigestRepository(db({list:[{id:'1',client_id:'c1'},{id:'2',client_id:'c2'}]}),{enabled:true});assert.equal((await r.inbox('c1')).length,1);await assert.rejects(()=>r.open('c1','m1'),/unavailable/);});
test('server failure and late signed-out replies cannot report success',async()=>{const r=createDigestRepository(db({rpcResult:()=>({error:{code:'40001'}})}),{enabled:true});await assert.rejects(()=>r.save('c1',0,valid),/Reload/);let finish;const late=createDigestRepository(db({rpcResult:()=>new Promise(resolve=>finish=resolve)}),{enabled:true});const pending=late.sample('c1',1);await new Promise(resolve=>setImmediate(resolve));late.clear();finish({data:'message'});await assert.rejects(()=>pending,/session has ended/);});
