import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {validateEvidence,createEvidenceRepository} from '../auth/evidence.mjs';
import {imageType,createHandler,MAX_IMAGE_BYTES} from '../supabase/functions/evidence-upload/handler.mjs';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aN8sAAAAASUVORK5CYII=','base64');
const file={name:'evidence.png',type:'image/png',size:png.length};
const details={kind:'webpage',capturedOn:'2026-10-01',sourceUrl:'https://example.test/product',notes:'Fictional evidence'};
function db({role='client',aal='aal1',user=true,list=[],invoke,image}={}){const calls=[];return {calls,auth:{getUser:async()=>({data:{user:user?{id:'u1'}:null}}),mfa:{getAuthenticatorAssuranceLevel:async()=>({data:{currentLevel:aal,nextLevel:role==='staff'?'aal2':aal}})}},rpc:async name=>{calls.push(name);return {data:role}},from(){return {select(){return this},eq(){return this},is(){return this},not(){return this},order:async()=>({data:list})}},functions:{invoke:async(...args)=>{calls.push('upload');return invoke?invoke(...args):{data:{evidence:{uploaded_at:'now'}}}}},storage:{from:()=>({download:image|| (async()=>({data:new Blob([png])}))})}};}
test('accepts dated webpage screenshots and photos without a webpage',()=>{assert.equal(validateEvidence(file,details,'2026-10-10').kind,'webpage');assert.equal(validateEvidence(file,{...details,kind:'photo',sourceUrl:''},'2026-10-10').sourceUrl,null);});
test('rejects wrong file types, zero bytes and oversized images',()=>{for(const f of [{...file,type:'image/svg+xml'},{...file,size:0},{...file,size:MAX_IMAGE_BYTES+1}])assert.throws(()=>validateEvidence(f,details),/PNG or JPEG/);});
test('rejects future/invalid dates, credential-bearing URLs and excessive notes',()=>{for(const d of [{...details,capturedOn:'2099-01-01'},{...details,capturedOn:'2026-02-30'},{...details,sourceUrl:'https://user:password@example.test'},{...details,sourceUrl:'javascript:alert(1)'},{...details,notes:'x'.repeat(1001)}])assert.throws(()=>validateEvidence(file,d,'2026-10-10'));});
test('disabled Production mode makes no requests',()=>{const d=db();assert.equal(createEvidenceRepository(d,'client',{enabled:false}),null);assert.deepEqual(d.calls,[]);});
test('list defensively removes other clients and marks',async()=>{const d=db({list:[{id:'1',client_id:'c1',mark_id:'m1'},{id:'2',client_id:'c2',mark_id:'m1'},{id:'3',client_id:'c1',mark_id:'m2'}]});assert.equal((await createEvidenceRepository(d,'client',{enabled:true}).list('c1','m1')).length,1);});
test('signed-out users and staff without MFA cannot read evidence',async()=>{for(const opt of [{user:false},{role:'staff',aal:'aal1'}])await assert.rejects(()=>createEvidenceRepository(db(opt),opt.role||'client',{enabled:true}).list('c1'));});
test('attorneys can read with MFA but cannot upload',async()=>{const repo=createEvidenceRepository(db({role:'staff',aal:'aal2'}),'staff',{enabled:true});await repo.list('c1');await assert.rejects(()=>repo.upload('c1','m1',file,details,'e1'),/Only clients/);});
test('late image replies after sign-out are discarded',async()=>{let done;const d=db({image:()=>new Promise(resolve=>done=resolve)}),repo=createEvidenceRepository(d,'client',{enabled:true});const pending=repo.image({object_path:'c1/image'});await new Promise(resolve=>setImmediate(resolve));repo.clear();done({data:new Blob([png])});await assert.rejects(()=>pending,/session has ended/);});
test('upload failure never reports a completed record',async()=>{const d=db({invoke:async()=>({error:new Error('offline')})});const repo=createEvidenceRepository(d,'client',{enabled:true});await assert.rejects(()=>repo.upload('c1','m1',new File([png],'evidence.png',{type:'image/png'}),details,'e1'),/not completed/);});
test('backend checks image structure rather than trusting MIME',()=>{assert.equal(imageType(png),'image/png');for(const b of [Buffer.from('<svg/>'),png.subarray(0,16),Buffer.from('<html>not an image</html>')])assert.equal(imageType(b),null);});
function backend({role='client',authorized=true,reserveError,uploadError,previous=png,finishError}={}){const calls=[];const stored={id:'e1',uploaded_by:'u1',object_path:'c1/m1/e1.png',uploaded_at:null};let number=0;const make=()=>{const service=number++>0;return {auth:{getUser:async()=>({data:{user:authorized?{id:'u1'}:null}})},rpc:async(name,args)=>{calls.push(name);if(name==='vb_session_role')return {data:role};if(name==='vb_reserve_evidence')return reserveError?{error:{code:reserveError}}:{data:stored};if(name==='vb_finish_evidence'){assert(service);return finishError?{error:{code:finishError}}:{data:{...stored,uploaded_at:'now'}}}},storage:{from:()=>({upload:async(path,bytes,options)=>{calls.push('store');assert.equal(options.upsert,false);return uploadError?{error:{message:'failed'}}:{data:{}}},download:async()=>({data:new Blob([previous])})})}}};return {calls,handler:createHandler({createClient:make,env:key=>({SUPABASE_URL:'https://example.test',SUPABASE_ANON_KEY:'public',SUPABASE_SERVICE_ROLE_KEY:'secret'})[key]})};}
function request({bytes=png,mime='image/png',origin='http://127.0.0.1:8012',token=true}={}){const form=new FormData();form.append('file',new File([bytes],'evidence.png',{type:mime}));for(const [k,v]of Object.entries({id:'e1',client:'c1',mark:'m1',details:JSON.stringify(details)}))form.append(k,v);return new Request('https://example.test/upload',{method:'POST',headers:{origin,...(token?{authorization:'Bearer test-token'}:{})},body:form});}
test('backend denies untrusted origins and missing/invalid sign-in before storage',async()=>{for(const opt of [{origin:'https://untrusted.test'},{token:false}]){const b=backend();assert([401,403].includes((await b.handler(request(opt))).status));assert(!b.calls.includes('store'));}const b=backend({authorized:false});assert.equal((await b.handler(request())).status,401);});
test('backend denies attorney uploads and cross-client reservations',async()=>{for(const opts of [{role:'staff'},{reserveError:'42501'}]){const b=backend(opts);assert.equal((await b.handler(request())).status,403);assert(!b.calls.includes('store'));}});
test('backend rejects spoofed or mismatched image content before reservation',async()=>{for(const opt of [{bytes:Buffer.from('<script/>')},{mime:'image/jpeg'}]){const b=backend();assert.equal((await b.handler(request(opt))).status,400);assert(!b.calls.includes('vb_reserve_evidence'));}});
test('backend bounds the incoming stream without trusting Content-Length',async()=>{const b=backend();assert.equal((await b.handler(new Request('https://example.test/upload',{method:'POST',headers:{origin:'http://127.0.0.1:8012',authorization:'Bearer test-token'},body:new Uint8Array(MAX_IMAGE_BYTES+65537)}))).status,413);assert(!b.calls.includes('store'));});
test('successful upload is validated, stored once and finalized',async()=>{const b=backend();assert.equal((await b.handler(request())).status,200);assert.deepEqual(b.calls,['vb_session_role','vb_reserve_evidence','store','vb_finish_evidence']);});
test('retry after a lost upload response accepts only matching original bytes',async()=>{const good=backend({uploadError:true});assert.equal((await good.handler(request())).status,200);const bad=backend({uploadError:true,previous:Buffer.from('changed')});assert.equal((await bad.handler(request())).status,409);assert(!bad.calls.includes('vb_finish_evidence'));});
test('revocation or completion failure does not return success',async()=>{for(const code of ['42501','22023']){const b=backend({finishError:code});assert.equal((await b.handler(request())).status,code==='42501'?403:503);}});

test('client and MFA attorney removals use the scoped protected RPC',async()=>{for(const audience of ['client','staff']){const d=db({role:audience,aal:audience==='staff'?'aal2':'aal1'});const repo=createEvidenceRepository(d,audience,{enabled:true});await repo.remove('c1','e1');assert(d.calls.includes('vb_remove_evidence'));}});
test('signed-out and non-MFA attorney removals are rejected before mutation',async()=>{for(const opt of [{user:false},{role:'staff',aal:'aal1'}]){const d=db(opt);await assert.rejects(()=>createEvidenceRepository(d,opt.role||'client',{enabled:true}).remove('c1','e1'));assert(!d.calls.includes('vb_remove_evidence'));}});
test('failed and late removals cannot be reported as success',async()=>{const d=db();const original=d.rpc;d.rpc=async(name,...args)=>name==='vb_remove_evidence'?{error:{code:'42501'}}:original(name,...args);await assert.rejects(()=>createEvidenceRepository(d,'client',{enabled:true}).remove('c1','e1'),/could not be removed/);let finish;d.rpc=async(name,...args)=>name==='vb_remove_evidence'?new Promise(resolve=>finish=resolve):original(name,...args);const repo=createEvidenceRepository(d,'client',{enabled:true}),pending=repo.remove('c1','e1');await new Promise(resolve=>setImmediate(resolve));repo.clear();finish({data:null});await assert.rejects(()=>pending,/session has ended/);});
